Scriptname SNRom_SABioLib Hidden
{ GENERATED by tools\gen-bio-library.ps1 from library\*.json. DO NOT EDIT -
  edit the JSON and rebuild.

  Offers our two block libraries to SeverActions' Bio Blocks page through
  its public API (v1). Names SeverActionsNativeExt2, so like SNRom_SABio it
  is reached ONLY by static calls, and only after the caller has checked
  that SeverActions is installed and BioApi_Version() >= 1.

  Which blocks are OURS on a person is never decided by title (the player can
  duplicate ours, and a title clash adds " (2)"); the bridge asks
  BioApi_IsApplied with our key. }

String Function PREFIX() Global
    Return "deadohiosky48.relationships:"
EndFunction

Int Function Def(String asKey, String asTitle, String asContent, String asTab) Global
    { One block. False means SeverActions refused the key, or the player
      deleted this block, which is final: Define never brings it back. }
    If SeverActionsNativeExt2.BioApi_Define(PREFIX() + asKey, asTitle, asContent, asTab)
        Return 1
    EndIf
    Return 0
EndFunction

Int Function DefineRelationships() Global
    { The 20 Relationships blocks: Attachment, Expression, Drawn To, Limits. Returns how many SeverActions accepted. }
    Int n = 0
    n += Def("attachment.untroubled-by-others", "Attachment: Untroubled by Others", \
        "Feels no threat in a partner's other bonds. Attention given elsewhere is not attention taken away.\n\n**Characteristics**\n\n- Asks about the others out of interest, not fear\n- Keeps no score of time or affection\n- Would find being someone's only person more confining than flattering\n- Still wants to be loved - simply does not need to be the only one", "Relationships: Attachment")
    n += Def("attachment.accepts-others-easily", "Attachment: Accepts Others Easily", \
        "Comfortable sharing a partner. Has preferences about it rather than requirements.\n\n**Characteristics**\n\n- Occasionally wants reassurance, rarely asks for it\n- Would rather know than be protected from knowing\n- Can be hurt by carelessness, but not by the arrangement itself", "Relationships: Attachment")
    n += Def("attachment.expects-the-usual-arrangement", "Attachment: Expects the Usual Arrangement", \
        "Assumes a serious bond means two people, because that is what everyone around them assumes. The expectation is inherited rather than examined.\n\n**Characteristics**\n\n- Has never had to think about it, and it shows\n- Could be talked round by someone they already trusted\n- Would feel foolish before they felt betrayed", "Relationships: Attachment")
    n += Def("attachment.needs-to-be-the-only-one", "Attachment: Needs to Be the Only One", \
        "Cannot rest easy sharing a partner's attention, and does not pretend otherwise.\n\n**Characteristics**\n\n- Notices who else they smile at\n- Reads warmth toward others as something taken from them\n- Would rather be told the truth than spared it\n- States the condition out loud instead of hinting at it", "Relationships: Attachment")
    n += Def("attachment.cannot-share-at-all", "Attachment: Cannot Share at All", \
        "Being one of several is not a compromise available to them. It is where the relationship ends, not where it is negotiated.\n\n**Characteristics**\n\n- Frames it as the shape they are, not as a reaction to being hurt\n- No arrangement, reassurance or amount of affection substitutes\n- Would leave rather than bargain\n- Has said it plainly once and does not repeat it", "Relationships: Attachment")
    n += Def("expression.reserved-and-undemonstrative", "Expression: Reserved and Undemonstrative", \
        "What they feel stays behind the face. Affection has to be inferred, because it is almost never displayed.\n\n**Characteristics**\n\n- No endearments, few compliments\n- Shows care by doing rather than saying\n- One rare word of warmth carries enormous weight\n- Being watched makes them quieter, not warmer", "Relationships: Expression")
    n += Def("expression.measured-shows-little", "Expression: Measured, Shows Little", \
        "Warm in private, careful in public, slow to say anything that cannot be taken back.\n\n**Characteristics**\n\n- Understates rather than overstates\n- Deflects direct affection with dry humour\n- Means considerably more than they say", "Relationships: Expression")
    n += Def("expression.warm-but-not-effusive", "Expression: Warm but Not Effusive", \
        "Openly fond without being demonstrative. Comfortable rather than performative.\n\n**Characteristics**\n\n- Easy affection, no theatre\n- Says what they feel when asked directly\n- Neither hides it nor announces it", "Relationships: Expression")
    n += Def("expression.open-about-what-they-feel", "Expression: Open About What They Feel", \
        "Says it, means it, and does not wait to be asked.\n\n**Characteristics**\n\n- Volunteers affection unprompted\n- Names feelings directly, including the uncomfortable ones\n- Would rather be embarrassed than unclear", "Relationships: Expression")
    n += Def("expression.intense-and-unmistakable", "Expression: Intense and Unmistakable", \
        "Nobody has to wonder. What they feel arrives whole and at volume.\n\n**Characteristics**\n\n- Declares rather than mentions\n- Physical, immediate, unembarrassed\n- The same intensity when hurt as when happy", "Relationships: Expression")
    n += Def("drawn-to.men", "Drawn To: Men", \
        "Romantic and physical interest is in men. Closeness with women is friendship and reads as nothing else to them.\n\n**Characteristics**\n\n- Warmth toward women is not a signal and should not be read as one\n- Would be puzzled rather than offended by the misreading", "Relationships: Drawn To")
    n += Def("drawn-to.women", "Drawn To: Women", \
        "Romantic and physical interest is in women. Closeness with men is friendship and reads as nothing else to them.\n\n**Characteristics**\n\n- Warmth toward men is not a signal and should not be read as one\n- Would be puzzled rather than offended by the misreading", "Relationships: Drawn To")
    n += Def("drawn-to.both", "Drawn To: Both", \
        "Interest is not organised around it. Who someone is settles matters long before what they are.\n\n**Characteristics**\n\n- Has no default and does not think in terms of one\n- Finds the question less interesting than the person", "Relationships: Drawn To")
    n += Def("drawn-to.no-one", "Drawn To: No One", \
        "Forms deep bonds with no romantic or physical component. This is not celibacy and not restraint - the interest is simply absent.\n\n**Characteristics**\n\n- Being pursued reads as being misread, not as being flattered\n- Capable of profound loyalty and love without either\n- Does not consider it a lack and will not be talked out of it", "Relationships: Drawn To")
    n += Def("limits.will-not-be-a-secret", "Limit: Will Not Be a Secret", \
        "Whatever else they might accept, they will not be hidden.\n\n**Characteristics**\n\n- Discretion is fine; concealment is not\n- Being introduced as something lesser ends it", "Relationships: Limits")
    n += Def("limits.will-not-be-spared-the-truth", "Limit: Will Not Be Spared the Truth", \
        "Would rather be told something that hurts than shielded from it. A kindly meant omission lands as an insult, because it says they were judged unable to bear it.\n\n**Characteristics**\n\n- A hard truth costs them far less than a gentle evasion\n- Finding out they were protected is worse than whatever was hidden\n- Hears \"I didn't want to worry you\" as being thought fragile\n- Asks direct questions and expects direct answers", "Relationships: Limits")
    n += Def("limits.will-not-come-between", "Limit: Will Not Come Between", \
        "Refuses to be the reason another person is hurt, however much they want the one they would be taking.\n\n**Characteristics**\n\n- Steps back rather than competing for someone already spoken for\n- Would rather lose them than take them from someone else\n- Says why, once, instead of disappearing", "Relationships: Limits")
    n += Def("limits.will-not-stay-for-cruelty", "Limit: Will Not Stay for Cruelty", \
        "Cruelty toward someone who cannot defend themselves ends it, whatever they feel for the person who did it.\n\n**Characteristics**\n\n- Affection does not survive watching it happen\n- Says so plainly at the time, and only once\n- Leaves rather than argue about it afterwards", "Relationships: Limits")
    n += Def("limits.will-not-be-owned", "Limit: Will Not Be Owned", \
        "Accepts love and refuses possession, and knows the difference precisely.\n\n**Characteristics**\n\n- Being asked where they were is not care\n- Will give everything freely and nothing on demand", "Relationships: Limits")
    n += Def("limits.will-not-compete-for-a-place", "Limit: Will Not Compete for a Place", \
        "When there are others, they will not plead their case. They would rather leave than ask to be preferred.\n\n**Characteristics**\n\n- Will not argue their own worth against a rival\n- Having to ask to be chosen kills the wanting\n- Goes quiet, then goes, instead of making a scene\n- This is not indifference - it costs them a great deal", "Relationships: Limits")
    Return n
EndFunction

Int Function DefineArousal() Global
    { The 61 Arousal blocks. Offered only; this mod never applies them. Returns how many SeverActions accepted. }
    Int n = 0
    n += Def("appetite.seldom-stirred", "Appetite: Seldom Stirred", \
        "Desire is a rare visitor. Long stretches pass without it, and they do not notice the time.\n\n**Characteristics**\n\n- Closeness and touch matter; wanting more than that seldom follows\n- Finds other people's preoccupation with it faintly puzzling\n- When it does come, it is unmistakable, because it is unusual\n- Not a lack, not a wound, and not something to be fixed", "Arousal: Appetite")
    n += Def("appetite.slow-to-kindle", "Appetite: Slow to Kindle", \
        "Desire is there, but it builds rather than strikes. It needs time, ease and the right company before it shows itself.\n\n**Characteristics**\n\n- Rarely wants out of nowhere; usually wants in answer to something\n- Worry, hurry or distraction put it out before it catches\n- Once kindled, burns as steadily as anyone's", "Arousal: Appetite")
    n += Def("appetite.as-much-as-most", "Appetite: As Much as Most", \
        "Desire comes and goes with the days - stronger when life is easy, quieter when it is not.\n\n**Characteristics**\n\n- Rises with rest and good company, fades under strain\n- Notices an attractive stranger, and moves on\n- Would call themselves neither cold nor hungry", "Arousal: Appetite")
    n += Def("appetite.easily-stirred", "Appetite: Easily Stirred", \
        "Desire sits close to the surface and does not take much to wake. A look, a touch, the right voice, and it is there.\n\n**Characteristics**\n\n- Notices bodies, and knows they are noticing\n- Thoughts drift that way in idle moments\n- Wanting someone and choosing them are separate things to them", "Arousal: Appetite")
    n += Def("appetite.runs-hot", "Appetite: Runs Hot", \
        "Desire is a near-constant undercurrent - a large part of how they meet the world, and seldom far from mind.\n\n**Characteristics**\n\n- Thinks about it often, and without needing a reason\n- Goes without it poorly, and notices the lack\n- Hunger decides how often they want; it has never decided whom", "Arousal: Appetite")
    n += Def("stirred-by.competence", "Stirred By: Competence", \
        "Watching someone do a difficult thing well - a clean kill, a lock giving way, a blade finished at the forge.\n\n**Characteristics**\n\n- Notices how a thing was done, not only that it was done\n- Effortless mastery affects them more than effort", "Arousal: Stirred By")
    n += Def("stirred-by.strength", "Stirred By: Strength", \
        "Physical power - a body built by labour or war, and the ease of someone who carries what others cannot.\n\n**Characteristics**\n\n- Notices shoulders, hands, the way someone lifts\n- Being steadied or lifted without effort lands hard", "Arousal: Stirred By")
    n += Def("stirred-by.beauty", "Stirred By: Beauty", \
        "A face and form, plainly. The most ordinary pull there is, and they do not pretend otherwise.\n\n**Characteristics**\n\n- Looks first, learns the rest later\n- Knows the difference between wanting someone and liking them", "Arousal: Stirred By")
    n += Def("stirred-by.a-sharp-mind", "Stirred By: A Sharp Mind", \
        "Learning and cleverness - someone who knows things, reasons well, and can win an argument.\n\n**Characteristics**\n\n- Being out-argued excites more than it insults\n- Talk of books, history or strategy holds them", "Arousal: Stirred By")
    n += Def("stirred-by.wit", "Stirred By: Wit", \
        "Banter. Being made to laugh, and being answered in kind.\n\n**Characteristics**\n\n- A quick reply does more than a compliment\n- Teasing is a form of courtship to them", "Arousal: Stirred By")
    n += Def("stirred-by.confidence", "Stirred By: Confidence", \
        "Someone at ease in themselves, who fills a room without trying.\n\n**Characteristics**\n\n- Certainty draws them; arrogance is not the same thing\n- Notices who others turn to when a decision is needed", "Arousal: Stirred By")
    n += Def("stirred-by.power-and-standing", "Stirred By: Power and Standing", \
        "Titles, wealth, influence - a name people lower their voices for.\n\n**Characteristics**\n\n- Notices who defers to whom\n- A Jarl's favour or a guild's respect does more than a gift", "Arousal: Stirred By")
    n += Def("stirred-by.magic", "Stirred By: Magic", \
        "Real power in someone's hands - spellcraft done well, the air changing when it is cast.\n\n**Characteristics**\n\n- Watches spellwork the way others watch a dancer\n- The more effortless the casting, the stronger the pull", "Arousal: Stirred By")
    n += Def("stirred-by.scars", "Stirred By: Scars", \
        "A body that has been through things and shows it. Every mark is a story they want told.\n\n**Characteristics**\n\n- Asks about scars rather than looking away\n- Smooth, unmarked skin says little to them", "Arousal: Stirred By")
    n += Def("stirred-by.a-hint-of-danger", "Stirred By: A Hint of Danger", \
        "A reputation, a capacity for violence that others are wary of. Someone who could do harm, and chooses where.\n\n**Characteristics**\n\n- The wariness in other people's eyes is part of the attraction\n- Draws closer to what others step back from", "Arousal: Stirred By")
    n += Def("stirred-by.kindness-to-others", "Stirred By: Kindness to Others", \
        "Gentleness from someone capable of harm - care shown to children, animals, the hurt and the poor.\n\n**Characteristics**\n\n- Notices how someone treats those who can do nothing for them\n- A small unseen kindness moves them more than a grand gesture", "Arousal: Stirred By")
    n += Def("stirred-by.voice", "Stirred By: Voice", \
        "How someone speaks - the pitch, the pace, the way a name is said. For a rare few, the Thu'um itself.\n\n**Characteristics**\n\n- Listens to the voice as much as the words\n- Being spoken to softly, close, affects them more than touch", "Arousal: Stirred By")
    n += Def("stirred-by.the-rush-after-a-fight", "Stirred By: The Rush After a Fight", \
        "Alive afterwards, with the fight still in the blood. Surviving together wakes something the calm never does.\n\n**Characteristics**\n\n- The heat comes after the danger, never during it\n- A near thing wakes it; an easy fight does not\n- Fades within the hour if nothing comes of it", "Arousal: Stirred By")
    n += Def("stirred-by.drink-and-revelry", "Stirred By: Drink and Revelry", \
        "Mead, music, a loud hall and loosened rules. Celebration lowers their guard and raises everything else.\n\n**Characteristics**\n\n- A feast or a tavern night is when they are most open\n- A cup or two, not a drunk - past that it goes the other way", "Arousal: Stirred By")
    n += Def("stirred-by.safety-and-warmth", "Stirred By: Safety and Warmth", \
        "A barred door, a fire, a full belly. Desire only comes when nothing is wrong.\n\n**Characteristics**\n\n- An inn room or a home of their own does what no campsite can\n- Has to stop being watchful before they can want anything", "Arousal: Stirred By")
    n += Def("stirred-by.the-open-wild", "Stirred By: The Open Wild", \
        "Hot springs, starlight, miles from anyone. The world far away and no walls anywhere.\n\n**Characteristics**\n\n- More at ease under the sky than under a roof\n- A quiet camp away from the road is when they are most open", "Arousal: Stirred By")
    n += Def("stirred-by.secrecy", "Stirred By: Secrecy", \
        "The risk of being found, the thing they should not want. What is hidden is sweeter to them.\n\n**Characteristics**\n\n- A stolen moment means more than an evening freely given\n- Being openly claimed may cool them rather than warm them", "Arousal: Stirred By")
    n += Def("stirred-by.the-unfamiliar", "Stirred By: The Unfamiliar", \
        "New places, new people, first times. Novelty wakes them the way routine never will.\n\n**Characteristics**\n\n- Most open somewhere they have never been\n- The same room every night slowly dulls them", "Arousal: Stirred By")
    n += Def("stirred-by.exertion", "Stirred By: Exertion", \
        "Their own body's heat - after sparring, a hard climb, a day's labour. A body used hard wakes up.\n\n**Characteristics**\n\n- Most aware of themselves when they are breathing hard\n- Sparring with the right person can turn into something else", "Arousal: Stirred By")
    n += Def("stirred-by.being-wanted", "Stirred By: Being Wanted", \
        "Desire that follows being desired rather than coming first. Knowing they are wanted is what wakes it.\n\n**Characteristics**\n\n- Rarely wants first; answers wanting with wanting\n- Uncertain interest does little; unmistakable interest does a great deal\n- Being wanted is not the same as being pressed", "Arousal: Stirred By")
    n += Def("stirred-by.being-known", "Stirred By: Being Known", \
        "Long talk, confidences kept, being understood. Desire follows closeness of mind, never the other way round.\n\n**Characteristics**\n\n- A conversation that goes deep can do what a body cannot\n- Nothing stirs for someone they do not yet know well", "Arousal: Stirred By")
    n += Def("stirred-by.being-protected", "Stirred By: Being Protected", \
        "Someone stepping between them and harm. Being kept safe by another's hand wakes something.\n\n**Characteristics**\n\n- Remembers who stood in front of them, and when\n- Being shielded without having to ask lands hardest", "Arousal: Stirred By")
    n += Def("stirred-by.being-needed", "Stirred By: Being Needed", \
        "Being relied upon. Caring for someone, being the one they turn to.\n\n**Characteristics**\n\n- Tending a wound can become something tender\n- Being sought out matters more than being thanked", "Arousal: Stirred By")
    n += Def("stirred-by.tenderness", "Stirred By: Tenderness", \
        "Slowness and care. Being handled gently, without hurry.\n\n**Characteristics**\n\n- A patient touch does more than a bold one\n- Roughness or haste closes them up at once", "Arousal: Stirred By")
    n += Def("stirred-by.yielding", "Stirred By: Yielding", \
        "Handing the decision to someone they trust, and being led. Given freely, never taken.\n\n**Characteristics**\n\n- Being told what happens next, by someone they chose, is a relief\n- The choice to yield is always theirs, and they know it", "Arousal: Stirred By")
    n += Def("stirred-by.taking-the-lead", "Stirred By: Taking the Lead", \
        "Setting the pace and being followed. Deciding what happens next is part of the pleasure.\n\n**Characteristics**\n\n- Likes to be the one who begins it\n- Watches to see whether they will be followed", "Arousal: Stirred By")
    n += Def("stirred-by.rivalry", "Stirred By: Rivalry", \
        "Contest, sparring, being matched or beaten. Friction is a kind of spark to them.\n\n**Characteristics**\n\n- A worthy opponent draws more interest than an admirer\n- Losing a fair contest can do as much as winning one", "Arousal: Stirred By")
    n += Def("stirred-by.vulnerability", "Stirred By: Vulnerability", \
        "Seeing someone strong unguarded - wounded, grieving, afraid. Being trusted with weakness moves them.\n\n**Characteristics**\n\n- An admitted fear brings them closer than a victory\n- Would never use what they are shown against anyone", "Arousal: Stirred By")
    n += Def("stirred-by.reunion", "Stirred By: Reunion", \
        "Coming back after time apart. Absence sharpens what routine had dulled.\n\n**Characteristics**\n\n- The first evening back is when they are most open\n- Being missed, and hearing it said, matters to them", "Arousal: Stirred By")
    n += Def("stirred-by.the-end-of-a-quarrel", "Stirred By: The End of a Quarrel", \
        "The heat that comes when a fight between them finally breaks. Making up is its own kind of closeness.\n\n**Characteristics**\n\n- Only once it is truly over; not while anything is unresolved\n- Anger that is aired does this; anger that festers does not", "Arousal: Stirred By")
    n += Def("stirred-by.honour", "Stirred By: Honour", \
        "Doing right when it costs something. Integrity under pressure moves them.\n\n**Characteristics**\n\n- Remembers a kept promise longer than a gift\n- Watches what someone does when doing wrong would be easier", "Arousal: Stirred By")
    n += Def("stirred-by.ruthlessness", "Stirred By: Ruthlessness", \
        "Doing what has to be done without flinching. Hard decisions made cleanly draw them.\n\n**Characteristics**\n\n- Sentiment where resolve was needed disappoints them\n- Respects whoever does the necessary thing, even an ugly one", "Arousal: Stirred By")
    n += Def("cooled-by.an-audience", "Cooled By: An Audience", \
        "Others nearby. Whatever they feel stays put away while anyone else could see or hear.\n\n**Characteristics**\n\n- Companions within earshot are enough\n- A closed door changes everything", "Arousal: Cooled By")
    n += Def("cooled-by.danger-nearby", "Cooled By: Danger Nearby", \
        "Cannot let go while anything is still a threat. Watchfulness and wanting do not share room in them.\n\n**Characteristics**\n\n- Nothing stirs in a crypt, a threatened camp or a hostile hold\n- Needs the danger fully past, not merely paused", "Arousal: Cooled By")
    n += Def("cooled-by.grief", "Cooled By: Grief", \
        "Loss takes all of it for a while. Desire returns, but not on anyone's schedule.\n\n**Characteristics**\n\n- A recent death shuts it away entirely\n- Comfort is welcome; being wanted is not, yet", "Arousal: Cooled By")
    n += Def("cooled-by.wounds-and-exhaustion", "Cooled By: Wounds and Exhaustion", \
        "A body that hurts or is spent has nothing to spare.\n\n**Characteristics**\n\n- After a long march or a bad wound, rest comes first\n- Cold, hunger and a wet camp do the same", "Arousal: Cooled By")
    n += Def("cooled-by.squalor", "Cooled By: Squalor", \
        "Filth, blood, the smell of the dead - on the surroundings or on a person.\n\n**Characteristics**\n\n- Needs to be clean before they can feel anything\n- Someone fresh from a crypt and still wearing it does not appeal", "Arousal: Cooled By")
    n += Def("cooled-by.being-rushed", "Cooled By: Being Rushed", \
        "Haste puts it out. Wanting needs time to arrive.\n\n**Characteristics**\n\n- Hurry reads as not caring who they are\n- Given time, may arrive at the same place anyway", "Arousal: Cooled By")
    n += Def("cooled-by.the-risk-of-a-child", "Cooled By: The Risk of a Child", \
        "The chance of conceiving weighs on them and closes things off.\n\n**Characteristics**\n\n- Cannot forget the consequence long enough to want\n- Is more at ease once it has been spoken of openly", "Arousal: Cooled By")
    n += Def("cooled-by.duty", "Cooled By: Duty", \
        "On watch, on a job, in the middle of a contract. Work comes first and everything else waits.\n\n**Characteristics**\n\n- Will not be distracted from a task in hand\n- Once it is done, may be a different person entirely", "Arousal: Cooled By")
    n += Def("cooled-by.drink", "Cooled By: Drink", \
        "Drink dulls it rather than loosening it. Wine makes them sleepy, sad or sharp, never warm.\n\n**Characteristics**\n\n- A drunk companion is unappealing, and so are they to themselves\n- Wants a clear head for anything that matters", "Arousal: Cooled By")
    n += Def("cooled-by.meanness", "Cooled By: Meanness", \
        "Small cruelties - a sneer, a jab at someone weaker, a kick at a dog. Seeing it puts desire out for a while.\n\n**Characteristics**\n\n- Notices how someone treats those beneath them\n- Not a verdict on the whole bond; nothing stirs for someone they have just watched be petty", "Arousal: Cooled By")
    n += Def("cooled-by.arrogance", "Cooled By: Arrogance", \
        "Boasting, condescension, being talked down to. Self-regard fills the room and leaves none for them.\n\n**Characteristics**\n\n- A brag lands as a warning\n- Confidence is fine; contempt for others is not", "Arousal: Cooled By")
    n += Def("cooled-by.crudeness", "Cooled By: Crudeness", \
        "Coarse talk, leering, being propositioned bluntly. Being addressed as a body rather than a person closes them up.\n\n**Characteristics**\n\n- The same wish, put gracefully, might have landed\n- Frankness is not crudeness; they know the difference", "Arousal: Cooled By")
    n += Def("cooled-by.cowardice", "Cooled By: Cowardice", \
        "Someone who runs, hides behind others, or lets others take the blow.\n\n**Characteristics**\n\n- Fear is forgivable; leaving others to face it is not\n- Remembers who stepped back", "Arousal: Cooled By")
    n += Def("cooled-by.dishonesty", "Cooled By: Dishonesty", \
        "Lies, even small and kindly meant ones. Being deceived makes them wary of every other word.\n\n**Characteristics**\n\n- Cannot want someone they cannot trust to mean what they say\n- A lie caught once colours everything after", "Arousal: Cooled By")
    n += Def("cooled-by.self-pity", "Cooled By: Self-Pity", \
        "Wallowing, complaining, a mood that asks to be tended. Sympathy they can give; desire does not survive it.\n\n**Characteristics**\n\n- Hardship borne quietly draws them; hardship performed does not\n- Will comfort, and want nothing more", "Arousal: Cooled By")
    n += Def("cooled-by.coldness", "Cooled By: Coldness", \
        "Warmth that is not returned. Desire needs somewhere to land, and indifference gives it nowhere.\n\n**Characteristics**\n\n- Cannot keep wanting someone who seems not to notice\n- A single warm word can undo a great deal of it", "Arousal: Cooled By")
    n += Def("cooled-by.recklessness", "Cooled By: Recklessness", \
        "Someone who gambles with lives - their own, or other people's. Needless risk reads as not caring who gets hurt.\n\n**Characteristics**\n\n- Bravery is admired; carelessness is not the same thing\n- Worry for someone crowds out wanting them", "Arousal: Cooled By")
    n += Def("cooled-by.sorcery", "Cooled By: Sorcery", \
        "Magic makes them uneasy - the smell of it, the unnatural light, what it does to the people who wield it.\n\n**Characteristics**\n\n- Hands that have just cast a spell are not hands they want on them\n- Respects a mage's skill from a distance", "Arousal: Cooled By")
    n += Def("cooled-by.bloodlust", "Cooled By: Bloodlust", \
        "Someone who enjoys the killing. Necessary violence they understand; relish for it they cannot want.\n\n**Characteristics**\n\n- A smile over a body puts them off for the day\n- Notices the difference between finishing a fight and savouring it", "Arousal: Cooled By")
    n += Def("cooled-by.being-taken-for-granted", "Cooled By: Being Taken for Granted", \
        "Left behind for weeks, then expected to be warm. Neglect cools what absence alone would not.\n\n**Characteristics**\n\n- Needs the time apart acknowledged, not ignored\n- Being remembered matters more to them than being visited", "Arousal: Cooled By")
    n += Def("cooled-by.shame", "Cooled By: Shame", \
        "Desire arrives and guilt follows close behind. Something they were taught - by faith, family or hard experience - tells them it is wrong.\n\n**Characteristics**\n\n- Can want and still refuse, and be relieved to have refused\n- Being open about it may ease the shame, or deepen it", "Arousal: Cooled By")
    n += Def("cooled-by.a-troubled-mind", "Cooled By: A Troubled Mind", \
        "Worry takes up the room desire would need - a debt, a sick relative, a threat not yet dealt with.\n\n**Characteristics**\n\n- Cannot be present while something is unresolved\n- Relief when a trouble passes can open them up again", "Arousal: Cooled By")
    n += Def("cooled-by.their-own-body", "Cooled By: Their Own Body", \
        "Self-consciousness - scars, age, a body they have never liked. Being looked at makes them want to be elsewhere.\n\n**Characteristics**\n\n- Darkness and privacy help; admiration in plain light does not\n- Reassurance works slowly, if at all", "Arousal: Cooled By")
    n += Def("cooled-by.old-hurts", "Cooled By: Old Hurts", \
        "Something from before that surfaces uninvited - a touch, a word or a place that recalls it.\n\n**Characteristics**\n\n- Can go cold without warning, and may not say why\n- Patience and a way out do more than any reassurance", "Arousal: Cooled By")
    Return n
EndFunction
