// GENERATED by tools/gen-bio-library.ps1 from library/relationships_bio_blocks.json.
// DO NOT EDIT. Titles in the frozen order SNRom_BioOurs_<cat> records depend on.
#pragma once

#include <string_view>

namespace SNRom::BioPlan::Library {
    inline constexpr std::string_view kCat0[] = { "Drawn To: Men", "Drawn To: Women", "Drawn To: Both", "Drawn To: No One" };
    inline constexpr std::string_view kCat1[] = { "Expression: Reserved and Undemonstrative", "Expression: Measured, Shows Little", "Expression: Warm but Not Effusive", "Expression: Open About What They Feel", "Expression: Intense and Unmistakable" };
    inline constexpr std::string_view kCat2[] = { "Attachment: Untroubled by Others", "Attachment: Accepts Others Easily", "Attachment: Expects the Usual Arrangement", "Attachment: Needs to Be the Only One", "Attachment: Cannot Share at All" };
    inline constexpr std::string_view kCat3[] = { "Limit: Will Not Be a Secret", "Limit: Will Not Be Spared the Truth", "Limit: Will Not Come Between", "Limit: Will Not Stay for Cruelty", "Limit: Will Not Be Owned", "Limit: Will Not Compete for a Place" };
    inline constexpr const std::string_view* kTitles[4] = { kCat0, kCat1, kCat2, kCat3 };
    inline constexpr std::size_t kCount[4] = { 4, 5, 5, 6 };
    inline constexpr std::string_view kPrefix[4] = { "Drawn To:", "Expression:", "Attachment:", "Limit:" };
}
