<#
.SYNOPSIS
    Generates src\scripts\SNRom_SABioLib.psc from the two bio block libraries.

.DESCRIPTION
    library\relationships_bio_blocks.json and library\arousal_bio_blocks.json
    are the source of truth for our blocks. This turns them into one Papyrus
    function per library that offers every block to SeverActions through its
    Bio Blocks API (BioApi_Define), so the text players see always matches the
    release they installed. build.ps1 runs it before compiling.

    A block's KEY is permanent. SeverActions identifies a block by it, so
    renaming a key would orphan the old block on every NPC carrying it. Change
    titles and text freely; never change a key.

    SeverActions refuses a "{" anywhere in a block, and caps titles at 80 bytes
    and content at 2000. Those are checked here, so a bad edit fails the build
    instead of failing silently in someone's game.
#>
$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
$out = Join-Path $root 'src\scripts\SNRom_SABioLib.psc'

function Read-Library([string]$name) {
    $path = Join-Path $root "library\$name"
    $bytes = [IO.File]::ReadAllBytes($path)
    return ([Text.Encoding]::UTF8.GetString($bytes) | ConvertFrom-Json).blocks
}

# Papyrus string literals understand \n, \t, \\ and \". Nothing else is
# escaped, so a literal backslash or quote in the text must be doubled here.
function Papyrus-String([string]$s) {
    $s = $s.Replace('\', '\\').Replace('"', '\"')
    $s = $s.Replace("`r`n", "`n").Replace("`n", '\n').Replace("`t", '\t')
    return '"' + $s + '"'
}

$keys = @{}
function Emit-Library($blocks, [string]$fn, [string]$what) {
    $lines = New-Object System.Collections.Generic.List[string]
    $lines.Add("Int Function $fn() Global")
    $lines.Add("    { $what. Returns how many SeverActions accepted. }")
    $lines.Add('    Int n = 0')
    foreach ($b in $blocks) {
        $k = [string]$b.key
        if ($k -notmatch '^[a-z0-9_\-.]{1,64}$') { throw "Bad key '$k' on block $($b.id)" }
        if ($keys.ContainsKey($k)) { throw "Duplicate key '$k'" }
        $keys[$k] = $true
        foreach ($f in @($b.title, $b.content)) {
            if ($f.Contains('{')) { throw "Block '$k' contains '{', which SeverActions refuses" }
        }
        if ([Text.Encoding]::UTF8.GetByteCount($b.title) -gt 80) { throw "Title of '$k' is over 80 bytes" }
        if ([Text.Encoding]::UTF8.GetByteCount($b.content) -gt 2000) { throw "Content of '$k' is over 2000 bytes" }
        $lines.Add('    n += Def(' + (Papyrus-String $k) + ', ' + (Papyrus-String $b.title) + ', \')
        $lines.Add('        ' + (Papyrus-String $b.content) + ', ' + (Papyrus-String $b.tab) + ')')
    }
    $lines.Add('    Return n')
    $lines.Add('EndFunction')
    return $lines
}

$rel = Read-Library 'relationships_bio_blocks.json'
$aro = Read-Library 'arousal_bio_blocks.json'

$text = New-Object System.Collections.Generic.List[string]
$text.Add('Scriptname SNRom_SABioLib Hidden')
$text.Add('{ GENERATED by tools\gen-bio-library.ps1 from library\*.json. DO NOT EDIT -')
$text.Add('  edit the JSON and rebuild.')
$text.Add('')
$text.Add('  Offers our two block libraries to SeverActions'' Bio Blocks page through')
$text.Add('  its public API (v1). Names SeverActionsNativeExt2, so like SNRom_SABio it')
$text.Add('  is reached ONLY by static calls, and only after the caller has checked')
$text.Add('  that SeverActions is installed and BioApi_Version() >= 1.')
$text.Add('')
$text.Add('  Which blocks are OURS on a person is never decided by title (the player can')
$text.Add('  duplicate ours, and a title clash adds " (2)"); the bridge asks')
$text.Add('  BioApi_IsApplied with our key. }')
$text.Add('')
$text.Add('String Function PREFIX() Global')
$text.Add('    Return "deadohiosky48.relationships:"')
$text.Add('EndFunction')
$text.Add('')
$text.Add('Int Function Def(String asKey, String asTitle, String asContent, String asTab) Global')
$text.Add('    { One block. False means SeverActions refused the key, or the player')
$text.Add('      deleted this block, which is final: Define never brings it back. }')
$text.Add('    If SeverActionsNativeExt2.BioApi_Define(PREFIX() + asKey, asTitle, asContent, asTab)')
$text.Add('        Return 1')
$text.Add('    EndIf')
$text.Add('    Return 0')
$text.Add('EndFunction')
$text.Add('')
(Emit-Library $rel 'DefineRelationships' "The $($rel.Count) Relationships blocks: Attachment, Expression, Drawn To, Limits") | ForEach-Object { $text.Add($_) }
$text.Add('')
(Emit-Library $aro 'DefineArousal' "The $($aro.Count) Arousal blocks. Offered only; this mod never applies them") | ForEach-Object { $text.Add($_) }

$utf8NoBom = New-Object Text.UTF8Encoding($false)
[IO.File]::WriteAllText($out, (($text -join "`r`n") + "`r`n"), $utf8NoBom)
Write-Host "Generated $out ($($rel.Count) Relationships + $($aro.Count) Arousal blocks)"

# The Relationships titles by key, in a script that names nothing of
# SeverActions', so the bridge can read it freely. Lets the bridge recognise
# our blocks among the titles one AssignedTitles call returns, instead of one
# BioApi_IsApplied call per block: each native call can cost a frame, and the
# load-time roster walk would otherwise make about a thousand of them.
$titlesOut = Join-Path $root 'src\scripts\SNRom_BioTitles.psc'
$t2 = New-Object System.Collections.Generic.List[string]
$t2.Add('Scriptname SNRom_BioTitles Hidden')
$t2.Add('{ GENERATED by tools\gen-bio-library.ps1 from library\relationships_bio_blocks.json.')
$t2.Add('  DO NOT EDIT. The title SeverActions shows for each of our Relationships keys. }')
$t2.Add('')
$t2.Add('String Function TitleOf(String asKey) Global')
$t2.Add('    { "" for a key that is not one of ours. }')
$first = $true
foreach ($b in $rel) {
    $kw = if ($first) { 'If' } else { 'ElseIf' }
    $first = $false
    $t2.Add("    $kw asKey == " + (Papyrus-String $b.key))
    $t2.Add('        Return ' + (Papyrus-String $b.title))
}
$t2.Add('    EndIf')
$t2.Add('    Return ""')
$t2.Add('EndFunction')
[IO.File]::WriteAllText($titlesOut, (($t2 -join "`r`n") + "`r`n"), $utf8NoBom)
Write-Host "Generated $titlesOut"
