<#
.SYNOPSIS
    Generates src\scripts\SNRom_SABioLib.psc from the two bio block libraries.

.DESCRIPTION
    library\relationships_bio_blocks.json and library\arousal_bio_blocks.json
    are the source of truth for our blocks. This turns them into one Papyrus
    function per library that offers every block to SeverActions through its
    Bio Blocks API (BioApi_Define), so the text players see always matches the
    release they installed. build.ps1 runs it before compiling.

    A block's KEY is permanent. SeverActions identifies a block by it, so
    renaming a key would orphan the old block on every NPC carrying it. Change
    titles and text freely; never change a key.

    SeverActions refuses a "{" anywhere in a block, and caps titles at 80 bytes
    and content at 2000. Those are checked here, so a bad edit fails the build
    instead of failing silently in someone's game.
#>
$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
$out = Join-Path $root 'src\scripts\SNRom_SABioLib.psc'

function Read-Library([string]$name) {
    $path = Join-Path $root "library\$name"
    $bytes = [IO.File]::ReadAllBytes($path)
    return ([Text.Encoding]::UTF8.GetString($bytes) | ConvertFrom-Json).blocks
}

# Papyrus string literals understand \n, \t, \\ and \". Nothing else is
# escaped, so a literal backslash or quote in the text must be doubled here.
function Papyrus-String([string]$s) {
    $s = $s.Replace('\', '\\').Replace('"', '\"')
    $s = $s.Replace("`r`n", "`n").Replace("`n", '\n').Replace("`t", '\t')
    return '"' + $s + '"'
}

$keys = @{}
function Emit-Library($blocks, [string]$fn, [string]$what) {
    $lines = New-Object System.Collections.Generic.List[string]
    $lines.Add("Int Function $fn() Global")
    $lines.Add("    { $what. Returns how many SeverActions accepted. }")
    $lines.Add('    Int n = 0')
    foreach ($b in $blocks) {
        $k = [string]$b.key
        if ($k -notmatch '^[a-z0-9_\-.]{1,64}$') { throw "Bad key '$k' on block $($b.id)" }
        if ($keys.ContainsKey($k)) { throw "Duplicate key '$k'" }
        $keys[$k] = $true
        foreach ($f in @($b.title, $b.content)) {
            if ($f.Contains('{')) { throw "Block '$k' contains '{', which SeverActions refuses" }
        }
        if ([Text.Encoding]::UTF8.GetByteCount($b.title) -gt 80) { throw "Title of '$k' is over 80 bytes" }
        if ([Text.Encoding]::UTF8.GetByteCount($b.content) -gt 2000) { throw "Content of '$k' is over 2000 bytes" }
        $lines.Add('    n += Def(' + (Papyrus-String $k) + ', ' + (Papyrus-String $b.title) + ', \')
        $lines.Add('        ' + (Papyrus-String $b.content) + ', ' + (Papyrus-String $b.tab) + ')')
    }
    $lines.Add('    Return n')
    $lines.Add('EndFunction')
    return $lines
}

$rel = Read-Library 'relationships_bio_blocks.json'
$aro = Read-Library 'arousal_bio_blocks.json'

$text = New-Object System.Collections.Generic.List[string]
$text.Add('Scriptname SNRom_SABioLib Hidden')
$text.Add('{ GENERATED by tools\gen-bio-library.ps1 from library\*.json. DO NOT EDIT -')
$text.Add('  edit the JSON and rebuild.')
$text.Add('')
$text.Add('  Offers our two block libraries to SeverActions'' Bio Blocks page through')
$text.Add('  its public API (v1). Names SeverActionsNativeExt2, so like SNRom_SABio it')
$text.Add('  is reached ONLY by static calls, and only after the caller has checked')
$text.Add('  that SeverActions is installed and BioApi_Version() >= 1.')
$text.Add('')
$text.Add('  Which blocks are OURS on a person is never decided by title (the player can')
$text.Add('  duplicate ours, and a title clash adds " (2)"); the bridge asks')
$text.Add('  BioApi_IsApplied with our key. }')
$text.Add('')
$text.Add('String Function PREFIX() Global')
$text.Add('    Return "deadohiosky48.relationships:"')
$text.Add('EndFunction')
$text.Add('')
$text.Add('Int Function Def(String asKey, String asTitle, String asContent, String asTab) Global')
$text.Add('    { One block. False means SeverActions refused the key, or the player')
$text.Add('      deleted this block, which is final: Define never brings it back. }')
$text.Add('    If SeverActionsNativeExt2.BioApi_Define(PREFIX() + asKey, asTitle, asContent, asTab)')
$text.Add('        Return 1')
$text.Add('    EndIf')
$text.Add('    Return 0')
$text.Add('EndFunction')
$text.Add('')
(Emit-Library $rel 'DefineRelationships' "The $($rel.Count) Relationships blocks: Attachment, Expression, Drawn To, Limits") | ForEach-Object { $text.Add($_) }
$text.Add('')
(Emit-Library $aro 'DefineArousal' "The $($aro.Count) Arousal blocks. Offered only; this mod never applies them") | ForEach-Object { $text.Add($_) }
$text.Add('')
# How many DefineAll offers, so the bridge can tell when SeverActions accepted
# fewer: blocks the player hid, which must not read as blocks taken off (2.1.1).
$text.Add('Int Function LibrarySize() Global')
$text.Add("    { How many blocks DefineRelationships and DefineArousal offer. }")
$text.Add("    Return $($rel.Count + $aro.Count)")
$text.Add('EndFunction')

$utf8NoBom = New-Object Text.UTF8Encoding($false)
[IO.File]::WriteAllText($out, (($text -join "`r`n") + "`r`n"), $utf8NoBom)
Write-Host "Generated $out ($($rel.Count) Relationships + $($aro.Count) Arousal blocks)"

# ---- the same titles for the DLL (native\src\BioLibrary.inl) ----------------
# SNRom_BioOurs_<cat> stores a block as its PLACE in its category (1 + index;
# Limits as bits), so that order is part of every save that has run 2.1. It is
# frozen here: a reordered or renamed key in the JSON fails the build instead
# of silently re-pointing every stored record. Append-only.
$frozen = @(
    @('drawn-to.men', 'drawn-to.women', 'drawn-to.both', 'drawn-to.no-one'),
    @('expression.reserved-and-undemonstrative', 'expression.measured-shows-little',
      'expression.warm-but-not-effusive', 'expression.open-about-what-they-feel',
      'expression.intense-and-unmistakable'),
    @('attachment.untroubled-by-others', 'attachment.accepts-others-easily',
      'attachment.expects-the-usual-arrangement', 'attachment.needs-to-be-the-only-one',
      'attachment.cannot-share-at-all'),
    @('limits.will-not-be-a-secret', 'limits.will-not-be-spared-the-truth', 'limits.will-not-come-between',
      'limits.will-not-stay-for-cruelty', 'limits.will-not-be-owned', 'limits.will-not-compete-for-a-place')
)
$tabs = @('Relationships: Drawn To', 'Relationships: Expression', 'Relationships: Attachment', 'Relationships: Limits')
$prefixes = @('Drawn To:', 'Expression:', 'Attachment:', 'Limit:')

function Cpp-String([string]$s) { return '"' + $s.Replace('\', '\\').Replace('"', '\"') + '"' }

$inl = New-Object System.Collections.Generic.List[string]
$inl.Add('// GENERATED by tools/gen-bio-library.ps1 from library/relationships_bio_blocks.json.')
$inl.Add('// DO NOT EDIT. Titles in the frozen order SNRom_BioOurs_<cat> records depend on.')
$inl.Add('#pragma once')
$inl.Add('')
$inl.Add('#include <string_view>')
$inl.Add('')
$inl.Add('namespace SNRom::BioPlan::Library {')
for ($c = 0; $c -lt 4; $c++) {
    $inCat = @($rel | Where-Object { $_.tab -eq $tabs[$c] })
    if ($inCat.Count -lt $frozen[$c].Count) { throw "$($tabs[$c]) has $($inCat.Count) blocks; the frozen order expects at least $($frozen[$c].Count)" }
    for ($i = 0; $i -lt $frozen[$c].Count; $i++) {
        if ($inCat[$i].key -ne $frozen[$c][$i]) {
            throw "$($tabs[$c]) entry $i is '$($inCat[$i].key)', but saved records expect '$($frozen[$c][$i])'. Never reorder or rename keys; append new ones."
        }
        if (-not $inCat[$i].title.StartsWith($prefixes[$c])) { throw "Title '$($inCat[$i].title)' does not start with '$($prefixes[$c])'" }
    }
    $names = ($inCat | ForEach-Object { Cpp-String $_.title }) -join ', '
    $inl.Add("    inline constexpr std::string_view kCat$c[] = { $names };")
}
$inl.Add('    inline constexpr const std::string_view* kTitles[4] = { kCat0, kCat1, kCat2, kCat3 };')
$counts = (0..3 | ForEach-Object { $c = $_; @($rel | Where-Object { $_.tab -eq $tabs[$c] }).Count }) -join ', '
$inl.Add("    inline constexpr std::size_t kCount[4] = { $counts };")
$inl.Add('    inline constexpr std::string_view kPrefix[4] = { ' + (($prefixes | ForEach-Object { Cpp-String $_ }) -join ', ') + ' };')
$inl.Add('}')
$inlOut = Join-Path $root 'native\src\BioLibrary.inl'
[IO.File]::WriteAllText($inlOut, (($inl -join "`r`n") + "`r`n"), $utf8NoBom)
Write-Host "Generated $inlOut"
